### Load kedro

In [1]:
import os

os.chdir("../../")

%load_ext kedro.ipython

[05/01/26 16:43:33] INFO     Using                                                                  ]8;id=991686;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=401299;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pac
                             kages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

[05/01/26 16:43:34] INFO     Registered line magic '%reload_kedro'                                   ]8;id=356172;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=900052;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=134132;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=761671;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=461062;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=229588;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\cxr-training-pipeli
                             ne.
                             To set a different path, run '%reload_kedro <project_root>'

[05/01/26 16:43:38] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=412300;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=567003;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\requests\__init__.py:113: RequestsDependencyWarning: urllib3
                             (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't
                             match a supported version!
                               warnings.warn(

[05/01/26 16:43:42] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=35262;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=935238;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=854506;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=812248;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#65\65]8;;\

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=379258;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=562210;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py#294\294]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics
                             /cxr-training-pipeline/mlruns'

[05/01/26 16:43:43] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=482827;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=228407;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:
                             The filesystem tracking backend (e.g., './mlruns') is deprecated as of
                             February 2026. Consider transitioning to a database backend (e.g.,
                             'sqlite:///mlflow.db') to take advantage of the latest MLflow
                             features. See
                             https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store
                             for migration guidance.
                               return FileStore(store_uri, store_uri)

[05/01/26 16:44:09] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=996453;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=440313;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[05/01/26 16:44:10] INFO     Kedro project cxr-training-pipeline                                    ]8;id=997647;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=602976;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=385131;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=349243;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=729777;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=541841;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

### Load mlflow

In [5]:
import mlflow

mlflow_context = context.config_loader.get("mlflow")

In [6]:
mlflow_context

{
    'server': {
        'mlflow_tracking_uri': None,
        'mlflow_registry_uri': None,
        'credentials': None,
        'request_header_provider': {'type': None, 'pass_context': False, 'init_kwargs': {}}
    },
    'tracking': {
        'disable_tracking': {'disable_autologging': True, 'pipelines': []},
        'experiment': {
            'name': 'cxr-classification-paper-resnet50',
            'create_experiment_kwargs': {'artifact_location': None, 'tags': None},
            'restore_if_deleted': True
        },
        'run': {'id': None, 'name': 'baseline_test_march', 'nested': True},
        'params': {
            'dict_params': {'flatten': False, 'recursive': True, 'sep': '.'},
            'long_params_strategy': 'fail'
        }
    },
    'ui': {'port': '5000', 'host': '127.0.0.1'}
}

In [ ]:
experiments = mlflow.search_experiments()

for exp in experiments:
    print(f"Experiment Name: {exp.name} | Experiment ID: {exp.experiment_id}")

Experiment Name: cxr-classification-paper-resnet50_224_40_epochs | Experiment ID: 203994855987655873
Experiment Name: cxr-classification-paper-resnet50 | Experiment ID: 318253955905806021
Experiment Name: cxr_training_pipeline_kedro_tests | Experiment ID: 668964428380772467
Experiment Name: cxr_training_pipeline | Experiment ID: 359151786460751498
Experiment Name: cxr_classification | Experiment ID: 713846466434312460

In [10]:
experiment_name = mlflow_context['tracking']['experiment']['name']

runs_df = mlflow.search_runs(
    experiment_names=[experiment_name],
)

runs_df.head(10)

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.train/loss,metrics.val/loss,metrics.best_model_score,metrics.val/auroc_micro,...,tags.mlflow.runName,tags.mlflow.user,tags.kedro_version,tags.project_path,tags.mlflow.source.name,tags.runner,tags.session_id,tags.kedro_command,tags.from_nodes,tags.Mode
0,5f73c6f7a9434c2b985cf24fd110c02c,318253955905806021,FINISHED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:41:29.278000+00:00,2026-03-31 20:31:28.121000+00:00,1.004820,1.009175,0.062294,0.735857,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.41.12.703Z,kedro run --pipeline=__default__,None,None
1,90b11e12c11d4958875fcafd9943c8d0,318253955905806021,FINISHED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:39:57.399000+00:00,2026-03-31 19:40:36.223000+00:00,NaN,NaN,NaN,NaN,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.39.41.195Z,kedro run --pipeline=__default__,None,None
2,73da5980c9084aff8a2841e9ce9d79be,318253955905806021,RUNNING,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:39:04.942000+00:00,NaT,NaN,NaN,NaN,NaN,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.38.47.446Z,kedro run --pipeline=__default__,None,None
3,44abf0d54fdd4123aff9c0f7704611b4,318253955905806021,FAILED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:36:37.471000+00:00,2026-03-31 19:36:42.641000+00:00,NaN,NaN,NaN,NaN,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.36.17.084Z,kedro run --pipeline=__default__,None,None
4,f6cf6816e9d94aca9fb99cda1922d1be,318253955905806021,FAILED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:20:05.540000+00:00,2026-03-31 19:32:05.765000+00:00,NaN,1.033672,NaN,0.704057,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.19.44.046Z,kedro run --pipeline=__default__,None,None
5,1f79da7c3b7d4538aa4b59e312d5e665,318253955905806021,FAILED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 19:03:48.569000+00:00,2026-03-31 19:15:46.947000+00:00,NaN,1.018156,NaN,0.716177,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T19.03.26.186Z,"kedro run --from-nodes=build_classifier_node,b...","['build_classifier_node', 'build_transforms_no...",None
6,706bffe49cd94b82b9586adbcb9c6354,318253955905806021,FAILED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-03-31 18:38:32.725000+00:00,2026-03-31 18:51:55.260000+00:00,1.040138,1.021492,NaN,0.721169,...,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-03-31T18.38.17.720Z,kedro run --pipeline=__default__,None,training

In [ ]:
def _get_run_info(run_id: str):
    mlflow_client = mlflow.tracking.MlflowClient()
    run = mlflow_client.get_run(RUN_ID)

    print("Run ID:", run.info.run_id)
    print("Experiment ID:", run.info.experiment_id)
    print("Start Time:", run.info.start_time)
    print("End Time:", run.info.end_time)
    print("Metrics:", run.data.metrics)
    print("Parameters:", run.data.params)
    print("Tags:", run.data.tags)

In [ ]:
RUN_ID = "5f73c6f7a9434c2b985cf24fd110c02c"

mlflow_client = mlflow.tracking.MlflowClient()
run = mlflow_client.get_run(RUN_ID)

print("Run ID:", run.info.run_id)
print("Experiment ID:", run.info.experiment_id)
print("Start Time:", run.info.start_time)
print("End Time:", run.info.end_time)
print("Metrics:", run.data.metrics)
print("Parameters:", run.data.params)
print("Tags:", run.data.tags)

Run ID: 5f73c6f7a9434c2b985cf24fd110c02c
Experiment ID: 318253955905806021
Start Time: 1774986089278
End Time: 1774989088121
Metrics: {'best_model_score': 0.062294118106365204, 'lr/opt0_group0': 0.0001, 'train/loss': 1.004820466041565, 'val/ap_macro': 0.06111924350261688, 'val/ap_micro': 0.10933420062065125, 'val/auroc_macro': 0.588997483253479, 'val/auroc_micro': 0.7358571290969849, 'val/loss': 1.0091749429702759}
Parameters: {'accumulate_grad_batches': '1', 'best_model_path': 'C:\\Users\\barte\\OneDrive\\Pulpit\\dnn-cxr-diagnostics\\cxr-training-pipeline\\checkpoints\\best-epoch=02-val_ap_macro=0.0000.ckpt', 'data_processing.columns_to_keep': "['image_index', 'finding_labels', 'patient_age', 'patient_sex', 'view_position']", 'data_processing.ohe_column': 'finding_labels', 'data_processing.pathology_list': "['Infiltration', 'Effusion', 'Atelectasis', 'Nodule', 'Mass', 'Pneumothorax', 'Consolidation', 'Pleural_Thickening', 'Cardiomegaly', 'Emphysema', 'Edema', 'Fibrosis', 'Pneumonia', 'Hernia']", 'data_processing_precompute.images_dir': 'data/01_raw/images', 'data_processing_precompute.image_col': 'image_index', 'data_processing_precompute.image_size': '224', 'data_processing_precompute.test_output_path': 'data/02_intermediate/precomputed/224/test_images.npy', 'data_processing_precompute.train_val_output_path': 'data/02_intermediate/precomputed/224/train_images.npy', 'data_processing_transforms': "{'resize': 224, 'grayscale': True, 'center_crop': 224, 'normalize': {'mean': [0.5], 'std': [0.5]}}", 'log_every_n_steps': '10', 'max_epochs': '4', 'mlflow_experiment_name': 'cxr-classification-paper-resnet50', 'patience': '5', 'precision': '16-mixed', 'threshold_tuning': "{'start': 0.01, 'stop': 1.0, 'step': 0.01, 'default_threshold': 0.5}", 'threshold_tuning.default_threshold': '0.5', 'training.classifier': "{'name': 'cxr_classifier', 'kwargs': {'num_classes': 14, 'transition_dim': 2048, 'pooling': 'lse', 'lse_r': 10.0, 'backbone_trainable_layers': ['layer4']}}", 'training.datamodule': "{'name': 'image_only', 'kwargs': {'batch_size': 32, 'num_workers': 0, 'train_val_images_path': 'data/02_intermediate/precomputed/224/train_images.npy', 'test_images_path': 'data/02_intermediate/precomputed/224/test_images.npy', 'y_train_val_path': 'data/02_intermediate/precomputed/224/train_labels.npy', 'y_test_path': 'data/02_intermediate/precomputed/224/test_labels.npy'}}", 'training.datamodule.name': 'image_only', 'training.lit_module': "{'name': 'default_classifier', 'kwargs': {'num_classes': 14, 'lr': 0.0001, 'threshold': 0.5}}", 'training.split': "{'val_size': 0.25, 'random_state': 42}", 'training.trainer': "{'max_epochs': 4, 'precision': '16-mixed', 'log_every_n_steps': 10, 'accumulate_grad_batches': 1, 'patience': 5, 'mlflow_experiment_name': 'cxr-classification-paper-resnet50'}", 'training.transforms': "{'random_rotation': 10, 'random_translate': [0.05, 0.05], 'random_scale': [0.95, 1.05]}"}
Tags: {'kedro_command': 'kedro run --pipeline=__default__', 'kedro_version': '1.2.0', 'mlflow.runName': 'baseline_test_march', 'mlflow.source.name': 'C:\\Users\\barte\\OneDrive\\Pulpit\\dnn-cxr-diagnostics\\.venv\\Scripts\\kedro', 'mlflow.source.type': 'LOCAL', 'mlflow.user': 'barte', 'project_path': 'C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics/cxr-training-pipeline', 'runner': '<kedro.runner.sequential_runner.SequentialRunner object at 0x00000224A583EF90>', 'session_id': '2026-03-31T19.41.12.703Z'}

In [12]:
metric_history = mlflow_client.get_metric_history(RUN_ID, "train/loss")

In [13]:
metric_history

[
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=0, timestamp=1774986776326, value=1.0414879322052002>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=1, timestamp=1774987481939, value=1.0414879322052002>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=1, timestamp=1774987488975, value=1.0325806140899658>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=2, timestamp=1774988165366, value=1.0325806140899658>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=2, timestamp=1774988173389, value=1.0176924467086792>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=3, timestamp=1774988759129, value=1.0176924467086792>,
    <Metric: dataset_digest=None, dataset_name=None, key='train/loss', model_id=None, run_id='5f73c6f7a9434c2b985cf24fd110c02c', step=3, timestamp=1774988759188, value=1.004820466041565>
]

### 40 epoch ResnetBackbone 224x224

In [16]:
NAME = "cxr-classification-paper-resnet50_224_40_epochs"

runs = mlflow.search_runs(experiment_names=[NAME])

runs.head()

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.train/loss,metrics.val/loss,metrics.best_model_score,metrics.val/auroc_micro,...,params.data_processing_precompute.image_size,tags.mlflow.source.type,tags.mlflow.runName,tags.mlflow.user,tags.kedro_version,tags.project_path,tags.mlflow.source.name,tags.runner,tags.session_id,tags.kedro_command
0,b9106a3d7476424abf0eaba9f15d5da7,203994855987655873,FINISHED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-04-01 20:14:58.787000+00:00,2026-04-02 01:38:15.675000+00:00,0.949071,0.940895,0.079001,0.768371,...,224,LOCAL,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-04-01T20.14.43.709Z,kedro run --pipeline=__default__
1,97519417b5e54a859487035a21088fe9,203994855987655873,FINISHED,file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr...,2026-04-01 20:14:11.161000+00:00,2026-04-01 20:14:23.425000+00:00,NaN,NaN,NaN,NaN,...,224,LOCAL,baseline_test_march,barte,1.2.0,C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnos...,C:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnos...,<kedro.runner.sequential_runner.SequentialRunn...,2026-04-01T20.13.31.936Z,kedro run --pipeline=__default__

In [17]:
ID = "203994855987655873"