In [1]:
import os

os.chdir("../../")

%load_ext kedro.ipython

[05/24/26 10:44:30] INFO     Using                                                                  ]8;id=954517;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=391990;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pac
                             kages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=892269;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=37408;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=311840;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=292332;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=154477;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=604349;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\cxr-training-pipeli
                             ne.
                             To set a different path, run '%reload_kedro <project_root>'

[05/24/26 10:44:35] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=295380;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=360367;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\requests\__init__.py:113: RequestsDependencyWarning: urllib3
                             (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't
                             match a supported version!
                               warnings.warn(

[05/24/26 10:44:42] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=759572;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=790440;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

[05/24/26 10:44:43] INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=451443;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=961506;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#65\65]8;;\

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=506030;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=413132;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py#294\294]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics
                             /cxr-training-pipeline/mlruns'

                    WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=290085;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=274431;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:
                             The filesystem tracking backend (e.g., './mlruns') is deprecated as of
                             February 2026. Consider transitioning to a database backend (e.g.,
                             'sqlite:///mlflow.db') to take advantage of the latest MLflow
                             features. See
                             https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store
                             for migration guidance.
                               return FileStore(store_uri, store_uri)

[05/24/26 10:45:24] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=558579;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=59487;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[05/24/26 10:45:25] INFO     Kedro project cxr-training-pipeline                                    ]8;id=388748;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=472793;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=683222;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=827268;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=958494;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=518300;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

In [2]:
FOLDER = REPORTING_FOLDER = os.path.join("data", "08_reporting")

os.listdir(FOLDER)

[
    '.gitkeep',
    'cxr-classification-densenet-161-224-no-scaling',
    'cxr-classification-densenet121-224-cropped',
    'cxr-classification-densenet121-224-no-scaling',
    'cxr-classification-densenet161-224-cropped',
    'cxr-classification-densenet169-224-cropped',
    'cxr-classification-efficientb0-224-no-scaling',
    'cxr-classification-efficientb7-224-no-scaling',
    'cxr-classification-efficientnet-b1-224-no-scaling',
    'cxr-classification-efficientnet-b2-224-no-scaling',
    'cxr-classification-efficientnet_b0-224-cropped',
    'cxr-classification-efficientnet_b1-224-cropped',
    'cxr-classification-efficientnet_b2-224-cropped',
    'cxr-classification-efficientnet_b7-224-cropped',
    'cxr-classification-paper-resnet50_224_40_epochs',
    'cxr-classification-resnet101-224-cropped',
    'cxr-classification-resnet101-224-no-scaling',
    'cxr-classification-resnet152-224-cropped-bce',
    'cxr-classification-resnet152-224-no-scaling',
    'cxr-classification-resnet18-224-cropped',
    'cxr-classification-resnet18-224-no-scaling',
    'cxr-classification-resnet50-224-cropped',
    'cxr-classification-resnet50-224-no-scaling'
]

In [3]:
EXP_NAME = "cxr-classification-resnet101-224-cropped"
RUN_NAME = "resnet101_224_cropped"


REPORTING_FOLDER = os.path.join("data", "08_reporting", EXP_NAME, RUN_NAME)

os.listdir(REPORTING_FOLDER)

[
    'best_thresholds.json',
    'localization_iou_metrics.json',
    'localization_iou_per_class.parquet',
    'localization_iou_per_image.parquet',
    'localization_weighted_iou_metrics.json',
    'localization_weighted_iou_per_image.parquet',
    'test_metrics_comparison.parquet',
    'test_metrics_default.json',
    'test_metrics_tuned.json',
    'test_per_class_after_tuning.parquet',
    'test_per_class_before_tuning.parquet',
    'test_per_class_comparison.parquet',
    'threshold_search_results.parquet'
]

In [4]:
import pandas as pd

test_metrics_per_class = pd.read_parquet(os.path.join(REPORTING_FOLDER, "test_per_class_before_tuning.parquet"))

In [5]:
test_metrics_per_class

,class_name,f1_default_0_5,precision_default_0_5,recall_default_0_5,accuracy,auroc_default_0_5,ap_default_0_5
0,Infiltration,0.453881,0.322186,0.767670,0.558876,0.688967,0.391726
1,Effusion,0.467591,0.329047,0.807643,0.665299,0.793809,0.452557
2,Atelectasis,0.340567,0.226158,0.689235,0.658072,0.740888,0.299573
3,Nodule,0.208941,0.129868,0.534196,0.743515,0.700856,0.182128
4,Mass,0.275069,0.191864,0.485698,0.825168,0.745118,0.236134
5,Pneumothorax,0.428179,0.314011,0.672795,0.812900,0.830095,0.377840
6,Consolidation,0.212115,0.129949,0.576860,0.696124,0.706825,0.139376
7,Pleural_Thickening,0.179967,0.114138,0.425197,0.826965,0.730449,0.109954
8,Cardiomegaly,0.332436,0.244288,0.520112,0.912760,0.840860,0.283273
9,Emphysema,0.267013,0.174950,0.563586,0.867870,0.824210,0.213392
10,Edema,0.197197,0.115865,0.661622,0.805321,0.830037,0.143566
11,Fibrosis,0.142539,0.094048,0.294253,0.939834,0.789530,0.078458
12,Pneumonia,0.074456,0.046803,0.181982,0.901899,0.656615,0.040482
13,Hernia,0.371257,0.382716,0.360465,0.995898,0.908994,0.296285

In [6]:
test_metrics_per_class_at = pd.read_parquet(os.path.join(REPORTING_FOLDER, "test_per_class_after_tuning.parquet"))

In [7]:
test_metrics_per_class_at

,class_name,f1_tuned,precision_tuned,recall_tuned,accuracy,auroc_tuned,ap_tuned,threshold_tuned
0,Infiltration,0.411490,0.262954,0.945681,0.354079,0.688967,0.391726,0.293457
1,Effusion,0.466811,0.327642,0.811507,0.662643,0.793809,0.452557,0.494629
2,Atelectasis,0.334053,0.214465,0.755108,0.614315,0.740888,0.299573,0.444092
3,Nodule,0.199405,0.120488,0.577942,0.705735,0.700856,0.182128,0.461426
4,Mass,0.256680,0.167962,0.544050,0.784810,0.745118,0.236134,0.426514
5,Pneumothorax,0.410695,0.285861,0.729081,0.782153,0.830095,0.377840,0.409180
6,Consolidation,0.219651,0.154171,0.381818,0.807626,0.706825,0.139376,0.644043
7,Pleural_Thickening,0.182363,0.112595,0.479440,0.808017,0.730449,0.109954,0.461182
8,Cardiomegaly,0.349877,0.368530,0.333022,0.948312,0.840860,0.283273,0.792480
9,Emphysema,0.273196,0.257490,0.290942,0.933896,0.824210,0.213392,0.868652
10,Edema,0.181008,0.102583,0.768649,0.748633,0.830037,0.143566,0.363281
11,Fibrosis,0.127451,0.136483,0.119540,0.972183,0.789530,0.078458,0.740723
12,Pneumonia,0.079556,0.053516,0.154955,0.922253,0.656615,0.040482,0.563965
13,Hernia,0.260870,0.517241,0.174419,0.996679,0.908994,0.296285,0.842773

In [8]:
test_metrics_default = pd.read_json(os.path.join(REPORTING_FOLDER, "test_metrics_default.json"), orient="index")

In [9]:
test_metrics_default

                        0
f1_macro         0.282229
f1_micro         0.332710
precision_macro  0.201135
precision_micro  0.223074
recall_macro     0.538665
recall_micro     0.654267
auroc_macro      0.770518
ap_macro         0.231767

In [10]:
test_metrics_tuned = pd.read_json(os.path.join(REPORTING_FOLDER, "test_metrics_tuned.json"), orient="index")

In [11]:
test_metrics_tuned

                        0
f1_macro         0.268079
f1_micro         0.329965
precision_macro  0.220142
precision_micro  0.217285
recall_macro     0.504725
recall_micro     0.685400
auroc_macro      0.770518
ap_macro         0.231767

In [12]:
from IPython.display import display

from cxr_training_pipeline.pipelines.testing.nodes import (
    compare_metrics_node,
    evaluate_default_thresholds_node,
    evaluate_tuned_thresholds_node,
)

pathology_list = catalog.load("params:data_processing.pathology_list")
default_threshold = catalog.load("params:threshold_tuning.default_threshold")

val_targets = catalog.load("val_targets")
val_pred_proba = catalog.load("val_pred_proba")
best_thresholds = catalog.load("best_thresholds")

val_metrics_default, val_per_class_before_tuning = evaluate_default_thresholds_node(
    val_targets,
    val_pred_proba,
    pathology_list,
    default_threshold,
)

val_metrics_tuned, val_per_class_after_tuning = evaluate_tuned_thresholds_node(
    val_targets,
    val_pred_proba,
    best_thresholds,
    pathology_list,
)

val_metrics_comparison, val_per_class_comparison = compare_metrics_node(
    val_metrics_default,
    val_metrics_tuned,
    val_per_class_before_tuning,
    val_per_class_after_tuning,
)

display(val_metrics_comparison)
display(val_per_class_comparison)

[05/24/26 10:45:26] INFO     Loading data from params:data_processing.pathology_list           ]8;id=692697;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=762176;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from params:threshold_tuning.default_threshold       ]8;id=121723;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=673099;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\
                             (MemoryDataset)...

                    INFO     Loading data from val_targets (NumpyMemmapDataset)...             ]8;id=149289;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=450741;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from val_pred_proba (NumpyMemmapDataset)...          ]8;id=491577;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=213927;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from best_thresholds (JSONDataset)...                ]8;id=861600;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=660076;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

            metric  default_0_5     tuned     delta
0         f1_macro     0.184084  0.203203  0.019119
1         f1_micro     0.244601  0.257378  0.012777
2  precision_macro     0.117176  0.147996  0.030820
3  precision_micro     0.156265  0.160664  0.004399
4     recall_macro     0.469182  0.436329 -0.032853
5     recall_micro     0.562690  0.646623  0.083933
6      auroc_macro     0.766236  0.766236  0.000000
7         ap_macro     0.155283  0.155283  0.000000

,class_name,f1_default_0_5,precision_default_0_5,recall_default_0_5,accuracy_x,auroc_default_0_5,ap_default_0_5,f1_tuned,precision_tuned,recall_tuned,accuracy_y,auroc_tuned,ap_tuned,threshold_tuned,f1_delta,precision_delta,recall_delta,auroc_delta,ap_delta
0,Infiltration,0.342032,0.248328,0.549304,0.663122,0.673406,0.275727,0.314271,0.190068,0.906903,0.369146,0.673406,0.275727,0.301270,-0.027760,-0.058260,0.357599,0.0,0.0
1,Effusion,0.401108,0.274324,0.745787,0.780084,0.846007,0.416179,0.393118,0.262677,0.780899,0.761916,0.846007,0.416179,0.459473,-0.007990,-0.011647,0.035112,0.0,0.0
2,Atelectasis,0.303608,0.195371,0.680749,0.699274,0.759644,0.247941,0.293376,0.182446,0.748440,0.652813,0.759644,0.247941,0.441406,-0.010232,-0.012925,0.067691,0.0,0.0
3,Nodule,0.150661,0.092654,0.402896,0.753456,0.642998,0.110749,0.140449,0.079539,0.599659,0.601637,0.642998,0.110749,0.410889,-0.010212,-0.013115,0.196763,0.0,0.0
4,Mass,0.222037,0.140786,0.525074,0.827008,0.755121,0.187873,0.214958,0.132333,0.572271,0.803476,0.755121,0.187873,0.462158,-0.007079,-0.008453,0.047198,0.0,0.0
5,Pneumothorax,0.196857,0.121140,0.525000,0.865332,0.785670,0.164285,0.221538,0.150000,0.423529,0.906431,0.785670,0.164285,0.612305,0.024682,0.028860,-0.101471,0.0,0.0
6,Consolidation,0.166702,0.098447,0.543568,0.818363,0.767395,0.101883,0.146893,0.150072,0.143845,0.944154,0.767395,0.101883,0.793945,-0.019809,0.051625,-0.399723,0.0,0.0
7,Pleural_Thickening,0.127557,0.076590,0.381295,0.865933,0.719319,0.077023,0.140083,0.086770,0.363309,0.885350,0.719319,0.077023,0.539551,0.012526,0.010180,-0.017986,0.0,0.0
8,Cardiomegaly,0.188994,0.111960,0.605839,0.901207,0.877359,0.185884,0.269767,0.258352,0.282238,0.970968,0.877359,0.185884,0.887207,0.080773,0.146391,-0.323601,0.0,0.0
9,Emphysema,0.135642,0.081174,0.412281,0.916925,0.792152,0.101995,0.213592,0.182573,0.257310,0.970043,0.792152,0.101995,0.779297,0.077950,0.101398,-0.154971,0.0,0.0
10,Edema,0.154885,0.089655,0.568513,0.901623,0.868957,0.124398,0.169231,0.100161,0.545190,0.915122,0.868957,0.124398,0.557129,0.014346,0.010506,-0.023324,0.0,0.0
11,Fibrosis,0.085878,0.050533,0.285714,0.911423,0.743067,0.057193,0.107955,0.076923,0.180952,0.956451,0.743067,0.057193,0.649902,0.022077,0.026390,-0.104762,0.0,0.0
12,Pneumonia,0.049400,0.029561,0.150215,0.937728,0.673837,0.020477,0.049400,0.029561,0.150215,0.937728,0.673837,0.020477,0.500000,0.000000,0.000000,0.000000,0.0,0.0
13,Hernia,0.051813,0.029940,0.192308,0.991540,0.822367,0.102349,0.170213,0.190476,0.153846,0.998197,0.822367,0.102349,0.876953,0.118399,0.160536,-0.038462,0.0,0.0