### Imports

In [1]:
import matplotlib.pyplot as plt
import pandas as pd

### Load kedro

In [2]:
import os

os.chdir("../../")

%load_ext kedro.ipython

[03/28/26 22:40:03] INFO     Using                                                                  ]8;id=901277;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=9406;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pac
                             kages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=361507;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=683097;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=607288;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=509441;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=542775;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=970627;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\cxr-training-pipeli
                             ne.
                             To set a different path, run '%reload_kedro <project_root>'

[03/28/26 22:40:06] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=887555;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=162977;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\requests\__init__.py:113: RequestsDependencyWarning: urllib3
                             (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't
                             match a supported version!
                               warnings.warn(

[03/28/26 22:40:09] WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=524794;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=916373;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\pyfunc\utils\data_validation.py:186: UserWarning: [33mAdd
                             type hints to the `predict` method to enable data validation and
                             automatic signature inference during model logging. Check
                             https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage
                             -in-pythonmodel for more details.[0m
                               color_warning(

                    INFO     Registering new custom resolver: 'km.random_name'                    ]8;id=726717;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py\mlflow_hook.py]8;;\:]8;id=53897;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\framework\hooks\mlflow_hook.py#65\65]8;;\

                    INFO     The 'tracking_uri' key in mlflow.yml is relative            ]8;id=899531;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=175495;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_mlflow\config\kedro_mlflow_config.py#294\294]8;;\
                             ('server.mlflow_(tracking|registry)_uri = mlruns'). It is
                             converted to a valid uri:
                             'file:///C:/Users/barte/OneDrive/Pulpit/dnn-cxr-diagnostics
                             /cxr-training-pipeline/mlruns'

                    WARNING  c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-pack ]8;id=881295;file://C:\Python312\Lib\warnings.py\warnings.py]8;;\:]8;id=139952;file://C:\Python312\Lib\warnings.py#112\112]8;;\
                             ages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:
                             The filesystem tracking backend (e.g., './mlruns') is deprecated as of
                             February 2026. Consider transitioning to a database backend (e.g.,
                             'sqlite:///mlflow.db') to take advantage of the latest MLflow
                             features. See
                             https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store
                             for migration guidance.
                               return FileStore(store_uri, store_uri)

[03/28/26 22:40:31] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=262718;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=14082;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/28/26 22:40:32] INFO     Kedro project cxr-training-pipeline                                    ]8;id=815851;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=64392;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=652791;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=479851;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[03/28/26 22:40:33] INFO     Registered line magic 'run_viz'                                        ]8;id=162566;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=593520;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

### Loading results

In [3]:
best_thresholds = catalog.load("best_thresholds")
test_metrics_default = catalog.load("test_metrics_default")
test_metrics_tuned = catalog.load("test_metrics_tuned")
test_metrics_comparison = catalog.load("test_metrics_comparison")
test_per_class_comparison = catalog.load("test_per_class_comparison")

[03/28/26 22:41:53] INFO     Loading data from best_thresholds (JSONDataset)...                ]8;id=540655;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=859517;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from test_metrics_default (JSONDataset)...           ]8;id=816504;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=382189;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from test_metrics_tuned (JSONDataset)...             ]8;id=99278;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=467233;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from test_metrics_comparison (ParquetDataset)...     ]8;id=731279;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=408815;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

[03/28/26 22:41:54] INFO     Loading data from test_per_class_comparison (ParquetDataset)...   ]8;id=104209;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=312414;file://c:\Users\barte\OneDrive\Pulpit\dnn-cxr-diagnostics\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [4]:
best_thresholds

{
    'Infiltration': 0.62,
    'Effusion': 0.77,
    'Atelectasis': 0.74,
    'Nodule': 0.38,
    'Mass': 0.44,
    'Pneumothorax': 0.43,
    'Consolidation': 0.68,
    'Pleural_Thickening': 0.47000000000000003,
    'Cardiomegaly': 0.45,
    'Emphysema': 0.3,
    'Edema': 0.5700000000000001,
    'Fibrosis': 0.24000000000000002,
    'Pneumonia': 0.32,
    'Hernia': 0.2
}

In [5]:
test_metrics_default

{
    'f1_macro': 0.08127488196699888,
    'f1_micro': 0.22439883492515073,
    'precision_macro': 0.047544997286771765,
    'precision_micro': 0.13754733275758985,
    'recall_macro': 0.3469236022329322,
    'recall_micro': 0.6088362861133574,
    'auroc_macro': 0.5557446720602883,
    'ap_macro': 0.09381726817085746
}

In [6]:
test_metrics_tuned

{
    'f1_macro': 0.09001897444977436,
    'f1_micro': 0.17962692868657404,
    'precision_macro': 0.09576734415100081,
    'precision_micro': 0.1879367119106899,
    'recall_macro': 0.09867834363331392,
    'recall_micro': 0.17202087774755567,
    'auroc_macro': 0.5557446720602883,
    'ap_macro': 0.09381726817085746
}

In [7]:
test_metrics_comparison

            metric  default_0_5     tuned     delta
0         f1_macro     0.081275  0.090019  0.008744
1         f1_micro     0.224399  0.179627 -0.044772
2  precision_macro     0.047545  0.095767  0.048222
3  precision_micro     0.137547  0.187937  0.050389
4     recall_macro     0.346924  0.098678 -0.248245
5     recall_micro     0.608836  0.172021 -0.436815
6      auroc_macro     0.555745  0.555745  0.000000
7         ap_macro     0.093817  0.093817  0.000000

In [8]:
test_per_class_comparison

,class_name,f1_default_0_5,precision_default_0_5,recall_default_0_5,auroc_default_0_5,ap_default_0_5,f1_tuned,precision_tuned,recall_tuned,auroc_tuned,ap_tuned,threshold_tuned,f1_delta,precision_delta,recall_delta
0,Infiltration,0.385788,0.239343,0.993946,0.589580,0.297654,0.280362,0.325753,0.246073,0.589580,0.297654,0.62,-0.105426,0.086410,-0.747873
1,Effusion,0.310029,0.183627,0.994848,0.631493,0.260327,0.303797,0.276226,0.337484,0.631493,0.260327,0.77,-0.006231,0.092599,-0.657364
2,Atelectasis,0.228019,0.128864,0.989021,0.587987,0.165435,0.212091,0.180648,0.256786,0.587987,0.165435,0.74,-0.015928,0.051784,-0.732235
3,Nodule,0.000000,0.000000,0.000000,0.558975,0.076015,0.042974,0.071023,0.030807,0.558975,0.076015,0.38,0.042974,0.071023,0.030807
4,Mass,0.000000,0.000000,0.000000,0.486930,0.069032,0.010712,0.084034,0.005721,0.486930,0.069032,0.44,0.010712,0.084034,0.005721
5,Pneumothorax,0.000000,0.000000,0.000000,0.440879,0.087650,0.051813,0.057870,0.046904,0.440879,0.087650,0.43,0.051813,0.057870,0.046904
6,Consolidation,0.134557,0.072228,0.981818,0.614948,0.099148,0.133877,0.109628,0.171901,0.614948,0.099148,0.68,-0.000680,0.037400,-0.809917
7,Pleural_Thickening,0.000000,0.000000,0.000000,0.506852,0.044682,0.001657,0.015625,0.000875,0.506852,0.044682,0.47,0.001657,0.015625,0.000875
8,Cardiomegaly,0.000000,0.000000,0.000000,0.639374,0.063514,0.099733,0.073043,0.157156,0.639374,0.063514,0.45,0.099733,0.073043,0.157156
9,Emphysema,0.000000,0.000000,0.000000,0.449761,0.036760,0.004983,0.027027,0.002745,0.449761,0.036760,0.30,0.004983,0.027027,0.002745
10,Edema,0.079456,0.041569,0.897297,0.645978,0.060119,0.072039,0.082749,0.063784,0.645978,0.060119,0.57,-0.007417,0.041180,-0.833514
11,Fibrosis,0.000000,0.000000,0.000000,0.590480,0.025195,0.000000,0.000000,0.000000,0.590480,0.025195,0.24,0.000000,0.000000,0.000000
12,Pneumonia,0.000000,0.000000,0.000000,0.526376,0.024341,0.046227,0.037118,0.061261,0.526376,0.024341,0.32,0.046227,0.037118,0.061261
13,Hernia,0.000000,0.000000,0.000000,0.510812,0.003570,0.000000,0.000000,0.000000,0.510812,0.003570,0.20,0.000000,0.000000,0.000000